#!/usr/bin/env bun
/**
 * Run BoxBox locally without Docker or air.
 *
 * Starts:
 * - Backend:  http://127.0.0.1:8080
 * - Frontend: http://127.0.0.1:5173
 *
 * The Vite dev server proxies /api and /health to the backend, so the app
 * behaves like the single-origin production build.
 */

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createServer } from "node:net";
import { homedir, tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawn, type Subprocess } from "bun";

const backendHost = process.env.BOXBOX_LOCAL_BACKEND_HOST ?? "127.0.0.1";
let backendPort = Number(process.env.BOXBOX_LOCAL_BACKEND_PORT ?? "8080");
const frontendHost = process.env.BOXBOX_LOCAL_FRONTEND_HOST ?? "127.0.0.1";
let frontendPort = Number(process.env.BOXBOX_LOCAL_FRONTEND_PORT ?? "5173");
const username = process.env.BOXBOX_LOCAL_USER ?? "admin";
const password = process.env.BOXBOX_LOCAL_PASSWORD ?? "admin";
const homePath = process.env.BOXBOX_LOCAL_HOME ?? homedir();
const localUser =
  process.env.USER ?? homePath.split("/").filter(Boolean).at(-1) ?? "user";
const repoRoot = resolve(import.meta.dir, "..");
const backendRoot = join(repoRoot, "backend");
const frontendRoot = join(repoRoot, "frontend");
const driveRoots = getLocalDriveRoots();

const colors = {
  reset: "\x1b[0m",
  cyan: "\x1b[36m",
  yellow: "\x1b[33m",
  green: "\x1b[32m",
  red: "\x1b[31m",
  dim: "\x1b[2m",
  bold: "\x1b[1m",
};

const prefixes = {
  frontend: `${colors.cyan}[FE]${colors.reset}`,
  backend: `${colors.yellow}[BE]${colors.reset}`,
};

const processes: Subprocess[] = [];
const lineHandlers = new WeakMap<Subprocess, (line: string) => void>();
const tempDir = mkdtempSync(join(tmpdir(), "boxbox-local-"));
const dataDir = join(tempDir, "data");
const quickAccessStubRoot = join(tempDir, "home-folders");
const viteConfigPath = join(
  frontendRoot,
  `.boxbox-local-vite.${process.pid}.config.ts`,
);
let shuttingDown = false;
let actualFrontendUrl = "";

const quickAccessFolders = [
  { name: "desktop", folder: "Desktop" },
  { name: "downloads", folder: "Downloads" },
  { name: "documents", folder: "Documents" },
  { name: "music", folder: "Music" },
  { name: "pictures", folder: "Pictures" },
  { name: "videos", folder: "Videos" },
] as const;

let quickAccessMounts: { name: string; folder: string; path: string }[] = [];

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

function getLocalDriveRoots(): string[] {
  const configured = process.env.BOXBOX_LOCAL_DRIVE_ROOTS;
  if (configured !== undefined) {
    return unique(
      configured
        .split(/[,:]/)
        .map((path) => path.trim())
        .filter(Boolean),
    );
  }

  return unique([
    "/media/devmon",
    `/media/${localUser}`,
    `/run/media/${localUser}`,
    "/mnt",
  ]).filter((path) => existsSync(path));
}

function writeDriveMounts(): string {
  return driveRoots
    .map(
      (path, index) => `  - name: ${yamlString(`drive-${index + 1}`)}
    path: ${yamlString(path)}
    read_only: false
    auto_discover: true`,
    )
    .join("\n");
}

function resolveQuickAccessPath(folder: string): string {
  const homeFolderPath = join(homePath, folder);
  if (existsSync(homeFolderPath)) return homeFolderPath;

  const stubPath = join(quickAccessStubRoot, folder);
  mkdirSync(stubPath, { recursive: true });
  return stubPath;
}

function getQuickAccessMounts(): typeof quickAccessMounts {
  return quickAccessFolders.map(({ name, folder }) => ({
    name,
    folder,
    path: resolveQuickAccessPath(folder),
  }));
}

function writeQuickAccessMounts(): string {
  return quickAccessMounts
    .map(
      ({ name, path }) => `  - name: ${yamlString(name)}
    path: ${yamlString(path)}
    read_only: false`,
    )
    .join("\n");
}

function cleanupStaleViteConfigs(): void {
  for (const file of readdirSync(frontendRoot)) {
    if (file.startsWith(".boxbox-local-vite.") && file.endsWith(".config.ts")) {
      rmSync(join(frontendRoot, file), { force: true });
    }
  }
}

function writeLocalConfig(): string {
  const configPath = join(tempDir, "config.yaml");
  quickAccessMounts = getQuickAccessMounts();

  const config = `# Generated by scripts/local-test.ts
port: ${backendPort}
host: ${yamlString(backendHost)}
jwt_secret: ${yamlString("boxbox-local-dev-only-jwt-secret")}
rate_limit_rps: 50
max_upload_mb: 10240
chunk_size_mb: 5
data_dir: ${yamlString(dataDir)}
allowed_origins: []
users:
  ${yamlString(username)}: ${yamlString(password)}
mount_points:
${writeDriveMounts()}
  - name: ${yamlString("root")}
    path: ${yamlString("/")}
    read_only: true
  - name: ${yamlString("home")}
    path: ${yamlString(homePath)}
    read_only: false
${writeQuickAccessMounts()}
  - name: ${yamlString("cwd")}
    path: ${yamlString(repoRoot)}
    read_only: false
`;

  writeFileSync(configPath, config);
  return configPath;
}

function writeViteConfig(): string {
  const config = `import tailwindcss from '@tailwindcss/vite';
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [tailwindcss(), sveltekit()],
  server: {
    host: ${JSON.stringify(frontendHost)},
    port: ${frontendPort},
    strictPort: true,
    proxy: {
      '/api': {
        target: ${JSON.stringify(`http://${backendHost}:${backendPort}`)},
        changeOrigin: true,
        ws: true
      },
      '/health': {
        target: ${JSON.stringify(`http://${backendHost}:${backendPort}`)},
        changeOrigin: true
      }
    }
  }
});
`;

  writeFileSync(viteConfigPath, config);
  return viteConfigPath;
}

function prefixStream(
  stream: ReadableStream<Uint8Array>,
  prefix: string,
  onLine?: (line: string) => void,
): void {
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  const processChunk = async () => {
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() || "";

        for (const line of lines) {
          if (line.trim()) {
            onLine?.(line);
            console.log(`${prefix} ${line}`);
          }
        }
      }

      if (buffer.trim()) {
        onLine?.(buffer);
        console.log(`${prefix} ${buffer}`);
      }
    } catch {
      // Stream closed.
    }
  };

  processChunk();
}

function spawnWithPrefix(
  name: keyof typeof prefixes,
  cmd: string[],
  cwd: string,
  env: Record<string, string> = {},
  onLine?: (line: string) => void,
): Subprocess {
  const prefix = prefixes[name];
  console.log(
    `${prefix} ${colors.dim}Starting: ${cmd.join(" ")}${colors.reset}`,
  );

  const childEnv = {
    ...process.env,
    ...env,
    FORCE_COLOR: "1",
  } as Record<string, string>;
  delete childEnv.NO_COLOR;

  const proc = spawn({
    cmd,
    cwd,
    stdout: "pipe",
    stderr: "pipe",
    env: childEnv,
  });

  const handleLine = (line: string) => {
    onLine?.(line);
    lineHandlers.get(proc)?.(line);
  };

  if (proc.stdout) prefixStream(proc.stdout, prefix, handleLine);
  if (proc.stderr)
    prefixStream(proc.stderr, `${prefix} ${colors.red}`, handleLine);
  processes.push(proc);

  proc.exited.then((code) => {
    if (code !== 0 && code !== null) {
      console.log(
        `${prefix} ${colors.red}Process exited with code ${code}${colors.reset}`,
      );
    }
  });

  return proc;
}

function waitForProcessOutput(
  proc: Subprocess,
  label: string,
  matches: (line: string) => boolean,
  timeoutMs = 30_000,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      reject(new Error(`${label} did not print a ready signal`));
    }, timeoutMs);

    const finish = (err?: Error) => {
      clearTimeout(timeout);
      if (err) reject(err);
      else resolve();
    };

    const previous = lineHandlers.get(proc);
    lineHandlers.set(proc, (line) => {
      previous?.(line);
      if (matches(line)) {
        lineHandlers.delete(proc);
        finish();
      }
    });

    proc.exited.then((code) => {
      if (lineHandlers.get(proc)) {
        lineHandlers.delete(proc);
        finish(new Error(`${label} exited before it became ready (${code})`));
      }
    });
  });
}

async function ensureStillRunning(
  proc: Subprocess,
  label: string,
  delayMs = 750,
): Promise<void> {
  await Bun.sleep(delayMs);
  if (proc.exitCode !== null) {
    throw new Error(`${label} exited during startup`);
  }
}

async function waitForUrl(
  url: string,
  label: string,
  proc?: Subprocess,
  timeoutMs = 30_000,
): Promise<void> {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    if (proc?.exitCode !== null) {
      throw new Error(`${label} process exited before it became ready`);
    }

    try {
      const response = await fetch(url);
      if (response.ok) return;
    } catch {
      // Not ready yet.
    }
    await Bun.sleep(500);
  }
  throw new Error(`${label} did not become ready at ${url}`);
}

async function getDescendantPids(pid: number): Promise<number[]> {
  const proc = spawn({
    cmd: ["pgrep", "-P", String(pid)],
    stdout: "pipe",
    stderr: "ignore",
  });

  const output = await new Response(proc.stdout).text();
  await proc.exited;

  const children = output
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map(Number)
    .filter((pid) => Number.isInteger(pid) && pid > 0);
  const descendants = await Promise.all(children.map(getDescendantPids));

  return [...children, ...descendants.flat()];
}

async function killProcessTree(
  proc: Subprocess,
  signal: "SIGTERM" | "SIGKILL",
): Promise<void> {
  const pid = proc.pid;
  const pids =
    typeof pid === "number" ? [...(await getDescendantPids(pid)), pid] : [];

  for (const targetPid of pids) {
    try {
      process.kill(targetPid, signal);
    } catch {
      // Process may already be dead.
    }
  }

  if (pids.length === 0) {
    try {
      proc.kill(signal);
    } catch {
      // Process may already be dead.
    }
  }
}

async function cleanupProcesses(): Promise<void> {
  for (const proc of processes) {
    await killProcessTree(proc, "SIGTERM");
  }

  await Bun.sleep(500);

  for (const proc of processes) {
    await killProcessTree(proc, "SIGKILL");
  }
}

async function cleanupTempFiles(): Promise<void> {
  rmSync(viteConfigPath, { force: true });

  rmSync(tempDir, { recursive: true, force: true });
}

async function shutdown(signal: string): Promise<void> {
  if (shuttingDown) return;
  shuttingDown = true;

  console.log(
    `\n${colors.dim}Received ${signal}, shutting down...${colors.reset}`,
  );

  await cleanupProcesses();
  await cleanupTempFiles();
  process.exit(0);
}

async function cleanupAfterFailure(): Promise<void> {
  await cleanupProcesses();
  await cleanupTempFiles();
}

async function ensureCommand(
  command: string,
  installHint: string,
): Promise<void> {
  const check = spawn({
    cmd: ["which", command],
    stdout: "ignore",
    stderr: "ignore",
  });
  await check.exited;
  if (check.exitCode !== 0) {
    throw new Error(`${command} is not installed. ${installHint}`);
  }
}

function isPortAvailable(host: string, port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const server = createServer();

    server.once("error", () => {
      resolve(false);
    });

    server.listen(port, host, () => {
      server.close(() => resolve(true));
    });
  });
}

async function findAvailablePort(
  host: string,
  preferredPort: number,
  label: string,
): Promise<number> {
  for (let port = preferredPort; port < preferredPort + 50; port++) {
    if (await isPortAvailable(host, port)) {
      if (port !== preferredPort) {
        console.log(
          `${colors.yellow}${label} port ${preferredPort} is busy; using ${port}.${colors.reset}`,
        );
      }
      return port;
    }
  }

  throw new Error(
    `No available port found from ${preferredPort} to ${preferredPort + 49}`,
  );
}

async function main(): Promise<void> {
  if (!existsSync(homePath)) {
    throw new Error(`BOXBOX_LOCAL_HOME does not exist: ${homePath}`);
  }

  cleanupStaleViteConfigs();
  mkdirSync(dataDir, { recursive: true });

  await ensureCommand("go", "Install Go to run the backend locally.");
  await ensureCommand("bun", "Install Bun to run the frontend locally.");

  backendPort = await findAvailablePort(backendHost, backendPort, "Backend");
  frontendPort = await findAvailablePort(
    frontendHost,
    frontendPort,
    "Frontend",
  );

  const configPath = writeLocalConfig();
  writeViteConfig();

  process.on("SIGINT", () => shutdown("SIGINT"));
  process.on("SIGTERM", () => shutdown("SIGTERM"));
  process.on("exit", () => {
    rmSync(viteConfigPath, { force: true });
    rmSync(tempDir, { recursive: true, force: true });
  });

  console.log(`
${colors.bold}${colors.green}BoxBox Local Test Mode${colors.reset}
${colors.dim}No Docker. No air. Temporary config is in ${tempDir}.${colors.reset}

Frontend: ${colors.bold}http://${frontendHost}:${frontendPort}${colors.reset}
Backend:  http://${backendHost}:${backendPort}
Login:    ${username} / ${password}
Mounts:   home -> ${homePath}
          quick -> ${quickAccessMounts.map(({ name, path }) => `${name}:${path}`).join(", ")}
          repo -> ${repoRoot}
          root -> / (read-only)
          drives -> ${driveRoots.length > 0 ? driveRoots.join(", ") : "none"}
Data:     ${dataDir}
`);

  spawnWithPrefix(
    "backend",
    ["go", "run", "./cmd/server", "-config", configPath],
    backendRoot,
    {
      FM_PORT: String(backendPort),
      FM_HOST: backendHost,
      FM_DATA_DIR: dataDir,
    },
  );

  await waitForUrl(
    `http://${backendHost}:${backendPort}/health`,
    "Backend",
    processes[processes.length - 1],
  );

  const frontend = spawnWithPrefix(
    "frontend",
    ["bunx", "vite", "--config", viteConfigPath],
    frontendRoot,
    {
      NODE_OPTIONS: `${process.env.NODE_OPTIONS ?? ""} --no-deprecation`.trim(),
    },
    (line) => {
      const match = line.match(/Local:\s+(https?:\/\/\S+)/);
      if (match?.[1]) {
        actualFrontendUrl = match[1].replace(/\/$/, "");
      }
    },
  );

  await waitForProcessOutput(
    frontend,
    "Frontend",
    (line) => line.includes("Local:") || line.includes("ready in"),
  );
  await ensureStillRunning(frontend, "Frontend");
  console.log(
    `${colors.green}${colors.bold}Ready:${colors.reset} ${actualFrontendUrl || `http://${frontendHost}:${frontendPort}`}`,
  );

  await new Promise(() => {});
}

main().catch(async (err) => {
  console.error(`${colors.red}Fatal error:${colors.reset}`, err);
  await cleanupAfterFailure();
  process.exit(1);
});
